### ISSUE TITLE
AttributeError: 'PyObject' object has no attribute 'get_doc'

### ISSUE THREAD

**Issue by soupytwist** [python-rope/rope#157]
File "/third_party/py/rope/refactor/rename.py", line 97, in get_changes
  File "/third_party/py/rope/refactor/rename.py", line 195, in rename_in_module
  File "/third_party/py/rope/refactor/occurrences.py", line 78, in find_occurrences
  File "/third_party/py/rope/refactor/occurrences.py", line 215, in __call__
  File "/third_party/py/rope/base/utils.py", line 11, in _wrapper
  File "/third_party/py/rope/refactor/occurrences.py", line 137, in get_pyname
  File "/third_party/py/rope/base/evaluate.py", line 76, in get_pyname_at
  File "/third_party/py/rope/base/evaluate.py", line 112, in get_primary_and_pyname_at
  File "/third_party/py/rope/base/evaluate.py", line 46, in eval_str2
  File "/third_party/py/rope/base/evaluate.py", line 31, in eval_node2
  File "/third_party/py/rope/base/ast.py", line 41, in walk
  File "/third_party/py/rope/base/ast.py", line 41, in walk
  File "/third_party/py/rope/base/ast.py", line 39, in walk
  File "/third_party/py/rope/base/evaluate.py", line 154, in _Attribute
  File "/third_party/py/rope/base/pynamesdef.py", line 42, in get_object
  File "/third_party/py/rope/base/pyobjectsdef.py", line 68, in get_parameter
  File "/third_party/py/rope/base/utils.py", line 28, in newfunc
  File "/third_party/py/rope/base/pynames.py", line 188, in get
  File "/third_party/py/rope/base/pyobjectsdef.py", line 39, in _infer_parameters
  File "/third_party/py/rope/base/utils.py", line 40, in newfunc
  File "/third_party/py/rope/base/oi/soi.py", line 46, in infer_parameter_objects
  File "/third_party/py/rope/base/oi/soi.py", line 151, in _parameter_objects
  File "/third_party/py/rope/base/oi/docstrings.py", line 99, in hint_param
AttributeError: 'PyObject' object has no attribute 'get_doc'

Seems to be introduced by #143. I will look into it when I get a chance. Noticed this when trying to rename a method. Will try to find some simple steps to reproduce.

**Comment by mcepl** [comment]
@emacsway #143 was your pull request, right?

**Comment by mcepl** [comment]
BTW, @soupytwist , could we get some reproduction steps, please?

**Comment by soupytwist** [comment]
Sorry for the delay, it took me a while to narrow this down to something that I can share. I think this is not so important an issue, more an abuse of the language in the code I'm refactoring.

Here's a contrived example to demonstrate. Possibly this could manifest in a more logical way.
```python
class SuperClass(object):
  def __init__(self):
    self.foo = None

class SubClass(SuperClass):
  def __init__(self):
    super(SubClass, self).__init__()
    self.bar = 3

  def foo(self):
    return self.bar
```

The assumption that rope makes is that if any parent class has an attribute with the same name as a method in a subclass, it is also a function. It's not an unreasonable assumption...

Feel free to close if you don't think this is an issue. Initially it seemed more problematic.

**Comment by mcepl** [comment]
> Feel free to close if you don't think this is an issue.

Of course, I won't do that. This is certainly a bug, we should make a difference between method and property. However, I am completely swamped with other work, so pull requests are very very much welcome.

**Comment by emacsway** [comment]
I think, there is an easy fix. I will try to fix at this weekend. Thanks.

**Comment by emacsway** [comment]
@soupytwist , sorry for delay in fix...

**Comment by soupytwist** [comment]
Thank you!!!
